"""
Raw DDL for the chromosome-partitioned variant tables.

These tables are managed outside SQLAlchemy's declarative system
because PostgreSQL `PARTITION BY LIST` clauses cannot be expressed
in SQLAlchemy 2.x metadata. The DDL strings here are the source of
truth for the partitioned parents on PostgreSQL; the matching
`Table()` objects registered in `model_variants.map_*` exist solely
so ORM/Core queries (SELECT/INSERT/UPDATE/DELETE) work transparently
against either backend.

Schema rationale:

- Composite PK `(chromosome, variant_id)` enables partition pruning
  for any query that filters by chromosome.
- `variant_id BIGINT GENERATED BY DEFAULT AS IDENTITY` lets the ETL
  insert deterministic IDs while still supporting auto-increment
  for ad-hoc inserts.
- 25 partition children: chr 1-22 + X(23) + Y(24) + MT(25).
- No physical FKs between variant tables — integrity is enforced by
  the ETL; partitioned tables in standard PG cannot be referenced
  by FKs from partitioned tables of different parents anyway.

Pattern adopted from BF4 (`biofilter/modules/db/core_ddl.py`); IGEM
extends `variant_masters` with `entity_id` / `assembly_id` nullable
columns to support the canonical Entity knowledge graph.
"""

from __future__ import annotations


def ddl_list_partitions(
    parent_table: str,
    part_prefix: str,
    chrom_min: int = 1,
    chrom_max: int = 25,
) -> list[str]:
    """
    Generate CREATE TABLE statements for chromosome partition children.

    Convention: ``<part_prefix>_chr_<n>`` for chromosomes 1..22 (autosomes),
    23 (X), 24 (Y), 25 (MT). The Alembic `_include_object` filter in
    ``env.py`` recognises this naming pattern and excludes the children
    from autogenerate diffs.
    """
    ddls: list[str] = []
    for chrom in range(chrom_min, chrom_max + 1):
        part_name = f"{part_prefix}_chr_{chrom}"
        ddls.append(
            f"CREATE TABLE IF NOT EXISTS {part_name} "
            f"PARTITION OF {parent_table} "
            f"FOR VALUES IN ({chrom});"
        )
    return ddls


def ddl_variant_masters() -> str:
    """
    One row per ALT allele in a given assembly.

    IGEM-specific columns (vs BF4):
      - ``entity_id``  : link to the canonical Entity; nullable, no FK
                         (partitioned tables can't easily participate in
                         FKs without complicating ETL).
      - ``assembly_id``: which genome assembly the coordinates refer to.
                         Nullable, no FK.
    """
    return """
    CREATE TABLE IF NOT EXISTS variant_masters (
        chromosome integer NOT NULL,
        variant_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        entity_id bigint NULL,
        assembly_id integer NULL,

        position_start bigint NOT NULL,
        position_end   bigint NOT NULL,

        reference_allele varchar(64) NOT NULL,
        alternate_allele varchar(256) NOT NULL,

        rsid varchar(32) NULL,

        variant_type varchar(20) NULL,
        allele_type  varchar(20) NULL,

        ac bigint NULL,
        an bigint NULL,
        af double precision NULL,
        grpmax varchar(32) NULL,
        grpmax_af double precision NULL,

        cadd_raw_score double precision NULL,
        cadd_phred double precision NULL,
        revel_max double precision NULL,
        spliceai_ds_max double precision NULL,
        pangolin_largest_ds double precision NULL,
        sift_max double precision NULL,
        polyphen_max double precision NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_masters PRIMARY KEY (chromosome, variant_id),

        CONSTRAINT uq_variant_masters_natkey UNIQUE
            (chromosome, position_start, position_end,
             reference_allele, alternate_allele),

        CONSTRAINT ck_variant_masters_pos
            CHECK (position_end >= position_start),
        CONSTRAINT ck_variant_masters_af
            CHECK (af IS NULL OR (af >= 0.0 AND af <= 1.0)),
        CONSTRAINT ck_variant_masters_ac_an CHECK (
            (ac IS NULL AND an IS NULL)
            OR (ac IS NOT NULL AND an IS NOT NULL
                AND ac >= 0 AND an >= 0 AND ac <= an)
        )
    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_molecular_effects() -> str:
    """
    One row per (variant allele × transcript × atomic consequence).

    Connected to ``variant_masters`` by the logical key
    ``(chromosome, variant_id)``. No physical FK.
    """
    return """
    CREATE TABLE IF NOT EXISTS variant_molecular_effects (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,
        variant_key varchar(256) NOT NULL,

        gene_id varchar(32) NULL,
        gene_symbol varchar(64) NULL,
        transcript_id varchar(32) NOT NULL,
        feature_type varchar(32) NULL,

        consequence_raw varchar(255) NULL,

        consequence_id integer NOT NULL,
        impact_id integer NULL,
        biotype_id integer NULL,
        consequence_group_id integer NULL,
        consequence_category_id integer NULL,

        consequence_rank integer NULL,
        impact_rank integer NULL,
        is_most_severe_for_annotation boolean NULL,
        is_most_severe_for_variant boolean NULL,

        most_severe_consequence_per_annotation_id integer NULL,
        most_severe_consequence_per_variant_id integer NULL,

        canonical boolean NULL,
        mane_select boolean NULL,
        mane_plus_clinical boolean NULL,

        hgvsc varchar(128) NULL,
        hgvsp varchar(128) NULL,
        cdna_position varchar(32) NULL,
        cds_position varchar(32) NULL,
        protein_position varchar(32) NULL,
        amino_acids varchar(32) NULL,
        codons varchar(64) NULL,
        ensp varchar(32) NULL,

        lof_flag boolean NULL,
        lof_confidence varchar(8) NULL,
        lof_filter varchar(128) NULL,
        lof_flags varchar(256) NULL,
        lof_info text NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_molecular_effects PRIMARY KEY
            (chromosome, variant_id, transcript_id, consequence_id),

        CONSTRAINT ck_vme_lof_conf CHECK (
            lof_confidence IS NULL
            OR lof_confidence IN ('HC', 'LC', 'Filtered', 'NA')
        )
    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_effect_predictions() -> str:
    """One row per predictor result per variant (optionally per transcript)."""
    return """
    CREATE TABLE IF NOT EXISTS variant_effect_predictions (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,

        predictor_key varchar(128) NOT NULL,
        transcript_id varchar(32) NULL,

        predictor_name varchar(64) NOT NULL,
        predictor_version varchar(32) NULL,

        score double precision NULL,
        classification varchar(64) NULL,
        details text NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_effect_predictions PRIMARY KEY
            (chromosome, variant_id, predictor_key)
    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_regulatory_elements() -> str:
    """One row per (variant × regulatory element × bio_context)."""
    return """
    CREATE TABLE IF NOT EXISTS variant_regulatory_elements (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,

        reg_element_key varchar(192) NOT NULL,

        regulatory_element_id varchar(64) NOT NULL,
        element_type varchar(32) NULL,
        bio_context varchar(128) NULL,

        score double precision NULL,
        details text NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_regulatory_elements PRIMARY KEY
            (chromosome, variant_id, reg_element_key)
    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_gene_regulatory_evidence() -> str:
    """One row per (variant × gene × QTL type × bio_context)."""
    return """
    CREATE TABLE IF NOT EXISTS variant_gene_regulatory_evidence (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,

        evidence_key varchar(256) NOT NULL,

        gene_id varchar(32) NOT NULL,
        bio_context varchar(128) NULL,
        qtl_type varchar(16) NOT NULL,

        beta double precision NULL,
        se double precision NULL,
        p_value double precision NULL,
        n integer NULL,

        effect_allele varchar(64) NULL,
        details text NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_gene_regulatory_evidence PRIMARY KEY
            (chromosome, variant_id, evidence_key),

        CONSTRAINT ck_vgre_p
            CHECK (p_value IS NULL OR (p_value >= 0.0 AND p_value <= 1.0))
    ) PARTITION BY LIST (chromosome);
    """.strip()


CORE_PARTITIONED: tuple[str, ...] = (
    "variant_masters",
    "variant_molecular_effects",
    "variant_effect_predictions",
    "variant_regulatory_elements",
    "variant_gene_regulatory_evidence",
)
"""Canonical list of chromosome-partitioned table names. Consumed by
`bootstrap_models`, `_create_tables`, the Alembic `_include_object`
filter, and migrations that touch all partitioned tables at once."""
