"""Tests for igem.modules.data.tables (read_table generic loader).

Each test exercises one calling convention of ``read_table`` so that the
file doubles as a usage reference: read the test name + body to see how
to call ``read_table`` for a given format / scenario.
"""
from __future__ import annotations

import pandas as pd
import pytest

from igem.modules.data import read_table


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture
def small_table_df() -> pd.DataFrame:
    """3-row generic table; no special semantics, just round-trip checks."""
    return pd.DataFrame(
        {
            "id": ["a", "b", "c"],
            "value": [1.0, 2.0, 3.0],
            "label": ["x", "y", "z"],
        }
    )


# ---------------------------------------------------------------------------
# Suffix dispatch
# ---------------------------------------------------------------------------
class TestReadTableSuffixDispatch:
    """Each suffix the dispatcher recognises gets one round-trip test."""

    def test_csv(self, tmp_path, small_table_df):
        # Usage: read_table("table.csv")  -> pd.read_csv under the hood
        path = tmp_path / "table.csv"
        small_table_df.to_csv(path, index=False)

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)

    def test_tsv(self, tmp_path, small_table_df):
        # Usage: read_table("table.tsv")  -> pd.read_table (sep="\t")
        path = tmp_path / "table.tsv"
        small_table_df.to_csv(path, sep="\t", index=False)

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)

    def test_txt_treated_as_tsv(self, tmp_path, small_table_df):
        # Usage: read_table("table.txt")  -> pd.read_table (.txt is tab-separated)
        path = tmp_path / "table.txt"
        small_table_df.to_csv(path, sep="\t", index=False)

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)

    def test_csv_gz_decompressed_transparently(self, tmp_path, small_table_df):
        # Usage: read_table("table.csv.gz")  -> pandas decompresses by suffix
        path = tmp_path / "table.csv.gz"
        small_table_df.to_csv(path, index=False, compression="gzip")

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)

    def test_tsv_gz_decompressed_transparently(self, tmp_path, small_table_df):
        # Usage: read_table("table.tsv.gz")
        path = tmp_path / "table.tsv.gz"
        small_table_df.to_csv(
            path, sep="\t", index=False, compression="gzip"
        )

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)

    def test_parquet(self, tmp_path, small_table_df):
        # Usage: read_table("table.parquet")  -> pd.read_parquet
        # Skipped if pyarrow is not installed (parquet is optional).
        pytest.importorskip("pyarrow")
        path = tmp_path / "table.parquet"
        small_table_df.to_parquet(path, index=False)

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)

    def test_unknown_suffix_falls_back_to_csv(self, tmp_path, small_table_df):
        # Usage: read_table("table.dat")  -> default fallback is pd.read_csv
        path = tmp_path / "table.dat"
        small_table_df.to_csv(path, index=False)

        out = read_table(path)

        pd.testing.assert_frame_equal(out, small_table_df)


# ---------------------------------------------------------------------------
# Path / kwargs forwarding
# ---------------------------------------------------------------------------
class TestReadTableInput:
    def test_accepts_string_path(self, tmp_path, small_table_df):
        # Usage: read_table(str(path))  -- str and Path are both accepted
        path = tmp_path / "table.csv"
        small_table_df.to_csv(path, index=False)

        out = read_table(str(path))

        assert len(out) == 3

    def test_kwargs_forwarded_to_underlying_reader(self, tmp_path):
        # Usage: read_table("table.csv", sep=";", comment="#")
        # Any kwargs passed go straight to the pandas reader chosen by
        # the suffix — here we override sep and skip comment lines.
        path = tmp_path / "table.csv"
        path.write_text(
            "# generated by simulate.py\n"
            "id;value\n"
            "a;1\n"
            "b;2\n"
        )

        out = read_table(path, sep=";", comment="#")

        assert list(out.columns) == ["id", "value"]
        assert len(out) == 2
