"""
UniProt Protein Relationship DTP.

Pipeline role:
- Runs AFTER all master DTPs (Genes, Proteins, Gene Ontology, Pathways).
- Reads relationship_data.parquet produced by dtp_protein_uniprot transform.
- No extract or transform steps — those belong to dtp_protein_uniprot.

What is loaded:
- EntityRelationship rows connecting proteins to:
    Genes         → relation_type "encodes"      (via HGNC ID)
    Gene Ontology → relation_type "part_of"      (via GO term ID)
    Pathways      → relation_type "in_pathway"   (via KEGG pathway ID)
    Transcriptomics → relation_type "has_transcript" (via RefSeq NM/NP ID)

  Target entities that have not been loaded yet are silently skipped;
  running this DTP again after loading the missing master data will
  pick them up automatically.
"""

from pathlib import Path
from typing import Optional

import pandas as pd

from igem_backend.modules.etl.mixins.base_dtp import DTPBase, ETLStepStats
from igem_backend.modules.etl.mixins.entity_query_mixin import EntityQueryMixin

# Processed folder of the parent master DTP (relative to the same base dir)
_PARENT_SOURCE = "protein_uniprot"


class DTP(DTPBase, EntityQueryMixin):

    DTP_NAME = "dtp_protein_uniprot_relationships"
    DTP_VERSION = "1.0.0"
    DTP_TYPE = "relationship"
    ROLLBACK_STRATEGY = "delete"

    def __init__(self, logger, debug_mode, datasource, package, session, db):
        super().__init__()
        self.logger = logger
        self.debug_mode = debug_mode
        self.data_source = datasource
        self.package = package
        self.session = session
        self.db = db

    # -------------------------------------------------------------------------
    # EXTRACT — no-op
    # -------------------------------------------------------------------------
    def extract(
        self, raw_dir: str
    ) -> tuple[bool, str, Optional[str], ETLStepStats]:
        msg = (
            f"[{self.DTP_NAME}] Extract not applicable — "
            "raw data is owned by dtp_protein_uniprot."
        )
        self.logger.log(msg, "INFO")
        return True, msg, None, ETLStepStats()

    # -------------------------------------------------------------------------
    # TRANSFORM — no-op
    # -------------------------------------------------------------------------
    def transform(
        self, raw_dir: str, processed_dir: str
    ) -> tuple[bool, str, ETLStepStats]:
        msg = (
            f"[{self.DTP_NAME}] Transform not applicable — "
            "relationship_data.parquet is generated by dtp_protein_uniprot."
        )
        self.logger.log(msg, "INFO")
        return True, msg, ETLStepStats()

    # -------------------------------------------------------------------------
    # LOAD
    # -------------------------------------------------------------------------
    def load(self, processed_dir: str) -> tuple[bool, str, ETLStepStats]:
        self.logger.log(f"[{self.DTP_NAME}] Load starting...", "INFO")

        # Relationship file lives in the *parent* DTP's folder
        parent_dir = (
            Path(processed_dir)
            / self.data_source.source_system.name
            / _PARENT_SOURCE
        )
        rel_file = parent_dir / "relationship_data.parquet"

        if not rel_file.exists():
            return (
                False,
                f"relationship_data.parquet not found at {rel_file} — "
                "run dtp_protein_uniprot (extract + transform) first.",
                ETLStepStats(errors=1),
            )

        try:
            df = pd.read_parquet(rel_file, engine="pyarrow")
        except Exception as e:
            return (
                False, f"Could not read parquet: {e}", ETLStepStats(errors=1)
            )

        if df.empty:
            return True, "No relationship rows to load.", ETLStepStats()

        from igem_backend.modules.db.models.model_entities import (
            EntityAlias,
            EntityRelationshipType,
            EntityType,
        )

        # --- Pre-load lookup tables into memory ---
        type_id_map: dict[str, int] = {
            et.name: et.id
            for et in self.session.query(EntityType).all()
        }
        rel_type_map: dict[str, int] = {
            rt.code: rt.id
            for rt in self.session.query(EntityRelationshipType).all()
        }

        protein_type_id = type_id_map.get("Proteins")
        if protein_type_id is None:
            return (
                False,
                "EntityType 'Proteins' not found.",
                ETLStepStats(errors=1),
            )

        # Pre-load source (protein) entities: UniProt accession → entity_id
        source_map: dict[str, int] = {
            a.alias_value: a.entity_id
            for a in self.session.query(EntityAlias).filter_by(
                type_id=protein_type_id,
                alias_type="code",
                xref_source="UNIPROT",
            ).all()
        }

        # Lazy cache: (type_id, alias_norm) → entity_id
        _target_cache: dict[tuple[int, str], Optional[int]] = {}

        def _resolve_target(
            target_type: str, target_id: str
        ) -> Optional[int]:
            tid = type_id_map.get(target_type)
            if tid is None:
                return None
            norm = target_id.strip().lower()
            key = (tid, norm)
            if key not in _target_cache:
                a = (
                    self.session.query(EntityAlias)
                    .filter(
                        EntityAlias.type_id == tid,
                        EntityAlias.alias_norm == norm,
                    )
                    .first()
                )
                _target_cache[key] = a.entity_id if a else None
            return _target_cache[key]

        total = created = skipped = warnings = 0
        BATCH = 500
        skipped_rows: list[dict] = []

        for i, (_, row) in enumerate(df.iterrows()):
            total += 1

            source_id = str(row.get("source_id") or "").strip()
            target_id = str(row.get("target_id") or "").strip()
            source_type = str(row.get("source_type") or "").strip()
            target_type = str(row.get("target_type") or "").strip()
            relation_type = str(row.get("relation_type") or "").strip()

            if not (
                source_id and target_id
                and source_type and target_type and relation_type
            ):
                warnings += 1
                continue

            entity_1_id = source_map.get(source_id)
            if entity_1_id is None:
                skipped += 1
                skipped_rows.append({
                    "source_id": source_id, "target_id": target_id,
                    "source_type": source_type, "target_type": target_type,
                    "relation_type": relation_type,
                    "skip_reason": "source_not_found",
                })
                continue

            entity_2_id = _resolve_target(target_type, target_id)
            if entity_2_id is None:
                skipped += 1
                skipped_rows.append({
                    "source_id": source_id, "target_id": target_id,
                    "source_type": source_type, "target_type": target_type,
                    "relation_type": relation_type,
                    "skip_reason": f"target_not_found:{target_type}",
                })
                continue

            rel_type_id = rel_type_map.get(relation_type)
            if rel_type_id is None:
                self.logger.log(
                    f"Unknown relation_type '{relation_type}' — skipping",
                    "WARNING",
                )
                warnings += 1
                continue

            self.get_or_create_relationship(
                entity_1_id=entity_1_id,
                entity_2_id=entity_2_id,
                relationship_type_id=rel_type_id,
                data_source_id=self.data_source.id,
                entity_1_type_id=type_id_map.get(source_type),
                entity_2_type_id=type_id_map.get(target_type),
                package_id=self.package.id,
                auto_commit=False,
            )
            created += 1

            if (i + 1) % BATCH == 0:
                try:
                    self.session.commit()
                    self.logger.log(
                        f"[{self.DTP_NAME}] Committed batch {i + 1}/{total}",
                        "DEBUG",
                    )
                except Exception as e:
                    self.session.rollback()
                    return (
                        False,
                        f"Batch commit failed at row {i + 1}: {e}",
                        ETLStepStats(errors=1),
                    )

        try:
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            return False, f"Final commit failed: {e}", ETLStepStats(errors=1)

        if skipped_rows:
            skip_file = parent_dir / "skipped_relationships.csv"
            pd.DataFrame(skipped_rows).to_csv(skip_file, index=False)
            self.logger.log(
                f"[{self.DTP_NAME}] {skipped} skipped rows written to "
                f"{skip_file}",
                "INFO",
            )

        stats = ETLStepStats(
            total=total,
            created=created,
            skipped=skipped,
            warnings=warnings,
        )
        msg = (
            f"[{self.DTP_NAME}] Load complete: "
            f"total={total} created={created} "
            f"skipped={skipped} warnings={warnings}"
        )
        self.logger.log(msg, "INFO")
        return True, msg, stats
