# Generated by Django 4.1.5 on 2023-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ge", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="termmap",
            old_name="count",
            new_name="qtd_links",
        ),
        migrations.RenameField(
            model_name="wordmap",
            old_name="count",
            new_name="qtd_links",
        ),
    ]
