# Generated by Django 4.1.5 on 2023-05-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0005_logs_alter_wfcontrol_source_file_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="status",
            field=models.CharField(
                choices=[("e", "Error"), ("w", "Warning"), ("s", "Success")],
                default="s",
                max_length=1,
            ),
        ),
    ]
