# Generated by Django 4.1.5 on 2023-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0006_logs_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogsCollector",
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="igem_version",
            field=models.CharField(default="0.1.0", max_length=15),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_collect",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_map",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_prepare",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_reduce",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="status",
            field=models.CharField(
                choices=[("c", "Current"), ("o", "Overwrite"), ("w", "workprocess")],
                default="w",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_collect",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_map",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_prepare",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_reduce",
            field=models.IntegerField(default=0),
        ),
    ]
