# Generated by Django 4.1.6 on 2023-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ge", "0007_delete_logscollector_wfcontrol_igem_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="igem_version",
            field=models.CharField(default="0.1.2", max_length=15),
        ),
        migrations.AlterField(
            model_name="wfcontrol",
            name="igem_version",
            field=models.CharField(default="0.1.2", max_length=15),
        ),
    ]
